# Generated by Django 5.2 on 2025-05-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='fullname',
            new_name='name',
        ),
    ]
